name: DssatWeb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - django
  - gdal
  - tqdm
  - netcdf4
  - scikit-learn
  - gunicorn
  - pip
  - pip:
      - django-colorfield==0.9.0
      - django-import-export==3.2.0
      - dssattools==2.1.3
      - fiona==1.9.6
      - geojson==3.1.0
      - geopandas==0.14.4
      - highcharts-core==1.8.1
      - pandas-highcharts==0.5.2
      - pillow==9.4.0
      - psycopg2==2.9.9
      - py==1.11.0
      - pyproj==3.6.1
      - rasterio==1.3.10
      - requests==2.32.3
      - shapely==2.0.4